### ISSUE TITLE
how to dont play audio

### ISSUE THREAD

**Issue by AhmadManzoor** [ricardodeazambuja/ricardodeazambuja.github.io#1]
Hi thank you so much for this code.
can you please help how can i play a custom audio instead of playing the recorder audio. i.e i changed the last two lines with this
` sr, audio = wav_read(io.BytesIO(riff))
  #wav = processed audio
  return wav, sr`

but ut still is playing the recorder audio. i also tried to tweek some code in <script> tag but couldn't help.

Thanks in advance

**Comment by ricardodeazambuja** [comment]
Sorry, but I think you are asking this in the wrong repository :)
Is this related to one of the posts in my personal blog? If so, could you specify so I can point you the way?

**Comment by AhmadManzoor** [comment]
thank you @ricardodeazambuja for your response actually yeah that question was about your blog post : _how to get audio in colab notebook i.e initializing mic and recording audio and then playing_
although i have sorted out that issue but now i have another question. that code snippet gives us .weba format of audio, how can we get .wav format moreover i want to change sample rate of audio, do you have any idea how can I achieve that? although there is a commented line about bitspersecond , but even when i change its value and uncomment it it doesnt seem to have any effect.

**Comment by ricardodeazambuja** [comment]
I created a library to make life easier. Have a look: https://github.com/ricardodeazambuja/colab_utils

**Comment by AhmadManzoor** [comment]
yes , i saw that one, actually thats a great contribution. but ricardo my question is how can i get voice of sample rate =16000. ? there is a line in the code of audio snippet i changed the value there but no effect

**Comment by ricardodeazambuja** [comment]
Which browser are you using? Afaik, chrome will always sample at 48k (doesn't matter the value there, that's why it's commented out), so a simple solution for you is to down sample the file to 16k using pure python after the file was received.

**Comment by AhmadManzoor** [comment]
yeah i would have to do that. thank you for your kind responses. thanks a lot :)
